import Head from 'next/head'
import { Inter } from 'next/font/google'
import LandingPage from '../../components/landingPage/landingPage'
import Carrusel from '../../components/carrusel/carrusel'


const items = [
  { id: 1, src: "https://flowbite.com/docs/images/carousel/carousel-1.svg" },
  { id: 2, src: "https://flowbite.com/docs/images/carousel/carousel-2.svg" },
  { id: 3, src: "https://flowbite.com/docs/images/carousel/carousel-3.svg" },
  { id: 4, src: "https://flowbite.com/docs/images/carousel/carousel-2.svg" },
];

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MicroHard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo scj.png"/>
      </Head>

      <main>
        <div>
         <LandingPage/> 
        </div>

    <div className=' pt-16 pb-20 pl-8 pr-8'>
      <div className="container mx-auto">

      <Carrusel>
      {items.map((item) => (
        <div key={item.id} className="px-2">
          <img
            src={item.src}
            alt="carousel item"
            className="w-full max-h-screen object-cover"
          />
        </div>
      ))}
      </Carrusel>
      </div>
      </div>

      </main>

    </>
  )
}
